quarkus:
  http:
    port: ${PORT:8080}

  datasource:
    db-kind: mysql
    username: test-quarkus
    password: 123
    jdbc:
      url: ${QUARKUS_DATASOURCE_URL:jdbc:mysql://localhost:3306/test-quarkus?autoReconnect=true}
      min-size: 0
      max-size: 10

bitcoin-api/mp-rest/url: https://alura-bitcoin.herokuapp.com
bitcoin-api/mp-rest/scope: javax.enterprise.context.RequestScoped
