version: '2.2'

services:
  prometheus-jvm:
    image: murilo/test-quarkus-prometheus-jvm:latest
    build:
      context: ../
      dockerfile: docker/prometheus/Dockerfile-jvm
    ports:
      - 9090:9090
    networks:
      - mysql-network
    depends_on:
      - app-jvm

  app-jvm:
    image: murilo/test-quarkus-app-jvm:latest
    #cpus: '2'
    #mem_limit: '300M'
    build:
      context: ../
      dockerfile: docker/app/Dockerfile-jvm
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql:3306/test-quarkus?autoReconnect=true
    networks:
      - mysql-network
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test-quarkus
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=test-quarkus
    ports:
      - 3306:3306
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
